services:
    heimdall:
        image: metakgporg/heimdall
        container_name: heimdall
        build: .
        restart: always
        env_file:
            - .env
        networks:
            metaploy-network:
                aliases:
                    - heimdall
        volumes:
            - nginx-config-volume:/etc/nginx/sites-enabled
            - ./credentials.json:/app/credentials.json
            - ./token.json:/app/token.json

networks:
    metaploy-network:
        external: true
        name: metaploy-network

volumes:
    nginx-config-volume:
        external: true
        name: metaploy-nginx-config-volume
